import { FullSchoolReport } from './types';

export const initialSchoolReport: FullSchoolReport = {
  info: {
    kingdomHeader: 'ព្រះរាជាណាចក្រកម្ពុជា',
    motto: 'ជាតិ សាសនា ព្រះមហាក្សត្រ',
    districtOffice: 'ការិយាល័យអប់រំ យុវជន និងកីឡាស្រុក',
    cluster: 'កម្រងស្ពានស្រែង',
    schoolName: 'សាលាបឋមសិក្សា រោគ',
    reportTitle: 'របាយការណ៍បូកសរុបលទ្ធផលការងារដំណាច់ឆ្នាំ',
    academicYear: '២០២៥-២០២៦',
    locationType: 'remote', // 1 នៅទីប្រជុំជន ……. តំបន់ធម្មតា …… ដាច់ស្រយាល ✅ មិនធម្មតា …….។
    partnerNGOs: 'អង្គការទស្សន:ពិភពលោក អង្គការកុមារកម្ពុជារីករាយ អង្គការសាលាបៃតង',
    roomsTotal: 15,
    roomsTeaching: 12,
    roomsNonTeaching: 3,
    reportDateKhmerLunar: 'ថ្ងៃសៅរ៍ ១៥រោច ខែបុស្ស ឆ្នាំម្សាញ់ សប្ដស័ក ព.ស.២៥៦៩',
    reportDateKhmerSolar: 'ថ្ងៃទី២១ ខែមីនា ឆ្នាំ២០២៦',
    autoDateEnabled: true,
    customReportDate: '2026-03-21',
  },
  students: {
    overall: {
      total: 252,
      female: 119,
      change: 1,
      transferredIn: 1,
      transferredOut: 0,
    },
    byGrade: [
      { grade: 1, total: 35, female: 15, change: '0', transferredIn: '0', transferredOut: '0' },
      { grade: 2, total: 42, female: 22, change: '0', transferredIn: '0', transferredOut: '0' },
      { grade: 3, total: 41, female: 21, change: '0', transferredIn: '0', transferredOut: '0' },
      { grade: 4, total: 49, female: 21, change: '0', transferredIn: '0', transferredOut: '0' },
      { grade: 5, total: 50, female: 23, change: '0', transferredIn: '0', transferredOut: '0' },
      { grade: 6, total: 35, female: 17, change: '1', transferredIn: '1', transferredOut: '0' },
    ],
    note: 'ចំពោះសិស្សទាំងនេះគឺយកសិស្សពិតប្រាកដនៅ ឆមាសទី២ ឆ្នាំសិក្សា២០២៥-២០២៦',
    classesByGrade: {
      g1: 1,
      g2: 2,
      g3: 2,
      g4: 2,
      g5: 2,
      g6: 1,
      totalClasses: 10,
      multigradeClasses: 0,
    },
  },
  staff: {
    overallStaff: { total: 17, female: 13, change: 0, dropouts: 0, retired: 0 },
    singleClassTeachers: { total: 12, female: 11, change: 0, dropouts: 0, retired: 0 },
    doubleClassTeachers: { total: 0, female: 0, change: 0, dropouts: 0, retired: 0 },
    multigradeTeachers: { total: 0, female: 0, change: 0, dropouts: 0, retired: 0 },
    principalTeaching: { total: 0, female: 0, change: 0, dropouts: 0, retired: 0 },
    otherStaff: {
      total: 3,
      female: 1,
      description: 'ក្នុងនោះមាន បណ្ណារក្ស ១ នាក់, កសិកម្ម ១ នាក់, រដ្ឋបាល ១ នាក់',
    },
  },
  finances: {
    periodNote: 'ចាប់ពីខែ តុលា ដល់ ខែ កញ្ញា',
    tableRows: [
      {
        id: 'fin-1',
        description: 'សាងសង់អគារសិក្សាពហុបំណង',
        quantity: '២ខ្នង ៣បន្ទប់',
        totalAmount: '',
        budgetSource: '- SOF\n- HCC\n- សហគមន៍',
        deficit: '',
      },
      {
        id: 'fin-2',
        description: 'ជួសជុលអគារ',
        quantity: '១ខ្នង ២បន្ទប់',
        totalAmount: '',
        budgetSource: '- SOF\n- HCC',
        deficit: '',
      },
      {
        id: 'fin-3',
        description: 'ធ្វើរបង(ភ្លើ)',
        quantity: '៤០ម៉ែត្រ',
        totalAmount: '',
        budgetSource: '- WVSI',
        deficit: '',
      },
      {
        id: 'fin-4',
        description: 'សង្គ្រោះនិងកែលម្អសោភ័ណភាពសាលា',
        quantity: 'ចាក់ដីទីធ្លាសាលា',
        totalAmount: '',
        budgetSource: '- WVSI\n- SOF\n- សហគមន៍',
        deficit: '',
      },
      {
        id: 'fin-5',
        description: 'សម្ភារបង្រៀន និងរៀន',
        quantity: 'សម្ភារតូចតាច សង្ខេប',
        totalAmount: '',
        budgetSource: '- SOF',
        deficit: '',
      },
      {
        id: 'fin-6',
        description: 'សម្ភារការិយាល័យ',
        quantity: 'គាំទ្រកិច្ចដំណើរ',
        totalAmount: '',
        budgetSource: '- SOF',
        deficit: '',
      },
    ],
    totalExpenditureRiel: '',
    totalDeficitRiel: '',
    newConstruction: {
      buildings: 2,
      rooms: 3,
      costRiel: '',
      sources: 'SOF, HCC, សហគមន៍',
    },
    repair: {
      buildings: 1,
      rooms: 2,
      costRiel: '',
      sources: 'SOF, HCC',
    },
    furnitureAndImprovement: {
      costRiel: '',
      sources: 'WVSI, SOF, សហគមន៍',
    },
    officeSupplies: {
      costRiel: '',
      sources: 'SOF',
    },
  },
  library: {
    activeRegular: 1,
    suboptimal: 0,
    none: 0,
  },
  academicResults: [
    {
      grade: 1,
      yearEndTotal: 31,
      yearEndFemale: 15,
      finalStudentsTotal: 31,
      finalStudentsFemale: 15,
      passedAverageTotal: 31,
      passedAverageFemale: 15,
      passedRetestTotal: 0,
      passedRetestFemale: 0,
      finalPassedTotal: 31,
      finalPassedFemale: 15,
      repeaterTotal: 0,
      repeaterFemale: 0,
      dropoutTotal: 0,
      dropoutFemale: 0,
    },
    {
      grade: 2,
      yearEndTotal: 42,
      yearEndFemale: 20,
      finalStudentsTotal: 42,
      finalStudentsFemale: 20,
      passedAverageTotal: 42,
      passedAverageFemale: 20,
      passedRetestTotal: 0,
      passedRetestFemale: 0,
      finalPassedTotal: 42,
      finalPassedFemale: 20,
      repeaterTotal: 0,
      repeaterFemale: 0,
      dropoutTotal: 0,
      dropoutFemale: 0,
    },
    {
      grade: 3,
      yearEndTotal: 41,
      yearEndFemale: 18,
      finalStudentsTotal: 41,
      finalStudentsFemale: 18,
      passedAverageTotal: 41,
      passedAverageFemale: 18,
      passedRetestTotal: 0,
      passedRetestFemale: 0,
      finalPassedTotal: 41,
      finalPassedFemale: 18,
      repeaterTotal: 0,
      repeaterFemale: 0,
      dropoutTotal: 0,
      dropoutFemale: 0,
    },
    {
      grade: 4,
      yearEndTotal: 49,
      yearEndFemale: 23,
      finalStudentsTotal: 47,
      finalStudentsFemale: 23,
      passedAverageTotal: 45,
      passedAverageFemale: 21,
      passedRetestTotal: 2,
      passedRetestFemale: 2,
      finalPassedTotal: 47,
      finalPassedFemale: 23,
      repeaterTotal: 0,
      repeaterFemale: 0,
      dropoutTotal: 2,
      dropoutFemale: 0,
    },
    {
      grade: 5,
      yearEndTotal: 50,
      yearEndFemale: 22,
      finalStudentsTotal: 50,
      finalStudentsFemale: 22,
      passedAverageTotal: 46,
      passedAverageFemale: 22,
      passedRetestTotal: 4,
      passedRetestFemale: 0,
      finalPassedTotal: 50,
      finalPassedFemale: 22,
      repeaterTotal: 0,
      repeaterFemale: 0,
      dropoutTotal: 0,
      dropoutFemale: 0,
    },
    {
      grade: 6,
      yearEndTotal: 33,
      yearEndFemale: 15,
      finalStudentsTotal: 31,
      finalStudentsFemale: 15,
      passedAverageTotal: 28,
      passedAverageFemale: 15,
      passedRetestTotal: 3,
      passedRetestFemale: 0,
      finalPassedTotal: 31,
      finalPassedFemale: 15,
      repeaterTotal: 0,
      repeaterFemale: 0,
      dropoutTotal: 2,
      dropoutFemale: 0,
    },
  ],
  academicPercentages: [
    { grade: '1', passedBeforeTestPct: '100%', passedRetestPct: '0%', finalPassedPct: '100%', repeaterPct: '0%', dropoutPct: '0%', notes: '' },
    { grade: '2', passedBeforeTestPct: '100%', passedRetestPct: '0%', finalPassedPct: '100%', repeaterPct: '0%', dropoutPct: '0%', notes: '' },
    { grade: '3', passedBeforeTestPct: '100%', passedRetestPct: '0%', finalPassedPct: '100%', repeaterPct: '0%', dropoutPct: '0%', notes: '' },
    { grade: '4', passedBeforeTestPct: '96%', passedRetestPct: '4%', finalPassedPct: '96%', repeaterPct: '0%', dropoutPct: '4%', notes: '' },
    { grade: '5', passedBeforeTestPct: '92%', passedRetestPct: '8%', finalPassedPct: '100%', repeaterPct: '0%', dropoutPct: '0%', notes: '' },
    { grade: '6', passedBeforeTestPct: '85%', passedRetestPct: '9%', finalPassedPct: '94%', repeaterPct: '0%', dropoutPct: '6%', notes: '' },
    { grade: 'សរុប', passedBeforeTestPct: '95%', passedRetestPct: '3.7%', finalPassedPct: '98.4%', repeaterPct: '0%', dropoutPct: '1.6%', notes: '' },
  ],
  postTestAcademicResults: [
    {
      grade: 'ថ្នាក់ទី ១',
      sem1Total: 31,
      sem1Female: 15,
      yearEndTotal: 31,
      yearEndFemale: 15,
      passedAvgTotal: 31,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 15,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 31,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 15,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
    {
      grade: 'ថ្នាក់ទី ២',
      sem1Total: 42,
      sem1Female: 21,
      yearEndTotal: 42,
      yearEndFemale: 21,
      passedAvgTotal: 42,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 21,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 42,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 21,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
    {
      grade: 'ថ្នាក់ទី ៣',
      sem1Total: 40,
      sem1Female: 21,
      yearEndTotal: 40,
      yearEndFemale: 21,
      passedAvgTotal: 40,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 21,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 40,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 21,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
    {
      grade: 'ថ្នាក់ទី ៤',
      sem1Total: 49,
      sem1Female: 21,
      yearEndTotal: 49,
      yearEndFemale: 21,
      passedAvgTotal: 49,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 21,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 49,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 21,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
    {
      grade: 'ថ្នាក់ទី ៥',
      sem1Total: 50,
      sem1Female: 24,
      yearEndTotal: 50,
      yearEndFemale: 24,
      passedAvgTotal: 50,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 24,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 50,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 24,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
    {
      grade: 'ថ្នាក់ទី ៦',
      sem1Total: 35,
      sem1Female: 17,
      yearEndTotal: 35,
      yearEndFemale: 17,
      passedAvgTotal: 35,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 17,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 35,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 17,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
    {
      grade: 'សរុប',
      sem1Total: 247,
      sem1Female: 119,
      yearEndTotal: 247,
      yearEndFemale: 119,
      passedAvgTotal: 247,
      passedAvgTotalPct: '100%',
      passedAvgFemale: 119,
      passedAvgFemalePct: '100%',
      passedRetestTotal: 0,
      passedRetestTotalPct: '0%',
      passedRetestFemale: 0,
      passedRetestFemalePct: '0%',
      finalPassedTotal: 247,
      finalPassedTotalPct: '100%',
      finalPassedFemale: 119,
      finalPassedFemalePct: '100%',
      repeaterTotal: 0,
      repeaterTotalPct: '0%',
      repeaterFemale: 0,
      repeaterFemalePct: '0%',
      dropoutTotal: 0,
      dropoutTotalPct: '0%',
      dropoutFemale: 0,
      dropoutFemalePct: '0%',
    },
  ],
  teachingEvaluation: {
    rows: [
      { grade: 1, goodTeachers: 1, mediumTeachers: 0, weakTeachers: 0, khmerPct: 100, mathPct: 95, socialPct: 95, sciencePct: 95, englishPct: 0 },
      { grade: 2, goodTeachers: 0, mediumTeachers: 2, weakTeachers: 0, khmerPct: 75, mathPct: 85, socialPct: 85, sciencePct: 75, englishPct: 0 },
      { grade: 3, goodTeachers: 0, mediumTeachers: 2, weakTeachers: 0, khmerPct: 85, mathPct: 75, socialPct: 85, sciencePct: 75, englishPct: 0 },
      { grade: 4, goodTeachers: 0, mediumTeachers: 2, weakTeachers: 0, khmerPct: 85, mathPct: 85, socialPct: 75, sciencePct: 75, englishPct: 60 },
      { grade: 5, goodTeachers: 1, mediumTeachers: 1, weakTeachers: 0, khmerPct: 100, mathPct: 100, socialPct: 95, sciencePct: 100, englishPct: 85 },
      { grade: 6, goodTeachers: 1, mediumTeachers: 0, weakTeachers: 0, khmerPct: 100, mathPct: 100, socialPct: 85, sciencePct: 95, englishPct: 85 },
    ],
    criteriaGood: 'គោរពវិន័យការងារ កិច្ចតែងការបង្រៀនទៀងទាត់និងត្រឹមត្រូវ អនុវត្ដវិធីសាស្រ្តបង្រៀនថ្មីៗ។',
    criteriaMedium: 'កិច្ចតែងការបង្រៀនទៀងទាត់និងត្រឹមត្រូវ អនុវត្ដគោលវិធីសិស្សមជ្ឈមណ្ឌល។',
    criteriaWeak: 'កិច្ចតែងការបង្រៀនមិនទៀងទាត់និងត្រឹមត្រូវ អនុវត្ដគោលវិធីគ្រូមជ្ឈមណ្ឌល រក្សាឯកសារសម្រាប់ការងារអធិការកិច្ច។',
  },
  girlsCounseling: {
    rows: [
      { id: 1, description: 'ចំនួនកុមារីគោលដៅ', g4Total: 0, g4Pct: '0%', g5Total: 0, g5Pct: '0%', g6Total: 0, g6Pct: '0%', other: '' },
      { id: 2, description: 'កុមារីមានបញ្ហា', g4Total: 0, g4Pct: '0%', g5Total: 0, g5Pct: '0%', g6Total: 0, g6Pct: '0%', other: '' },
      { id: 3, description: 'កុមារីមានបញ្ហាដែលបានជួយ', g4Total: 0, g4Pct: '0%', g5Total: 0, g5Pct: '0%', g6Total: 0, g6Pct: '0%', other: '' },
    ],
    activities: 'លោកគ្រូ អ្នកគ្រូ និងគណៈគ្រប់គ្រងបានចុះជួបផ្ទាល់ជាមួយអាណាព្យាបាលសិស្សស្រី និងរៀបចំបន្ទប់ប្រឹក្សាយោបល់។',
    challenges: 'កុមារីមួយចំនួននៅមានការអៀនខ្មាស មិនហ៊ានបើកចំហរពីបញ្ហាផ្ទាល់ខ្លួន។',
    requests: 'សូមបន្តបណ្តុះបណ្តាលគ្រូទទួលបន្ទុកទីប្រឹក្សាកុមារីអំពីបច្ចេកទេសប្រឹក្សាផ្លូវចិត្ត និងសម្ភារៈឧបទេស។',
  },
  lifeSkills: {
    programs: [
      { name: 'អប់រំបង្ការជម្ងឺអេដស៍ និងបញ្ហាពាក់ព័ន្ធ', schoolsCount: 0, schoolsPct: '0%', studentsTotal: 0, studentsTotalPct: '0%', studentsFemale: 0, studentsFemalePct: '0%', notes: '' },
      { name: 'អប់រំអំពីបញ្ហាគ្រឿងញៀន', schoolsCount: 0, schoolsPct: '0%', studentsTotal: 0, studentsTotalPct: '0%', studentsFemale: 0, studentsFemalePct: '0%', notes: '' },
      { name: 'អប់រំបង្ការជម្ងឺឆ្លងនានា (គ្រុនចាញ់/ឈាម និងផ្ដាសាយថ្មី)', schoolsCount: 0, schoolsPct: '0%', studentsTotal: 0, studentsTotalPct: '0%', studentsFemale: 0, studentsFemalePct: '0%', notes: '' },
      { name: 'អប់រំអំពីអនាម័យមាត់ធ្មេញ', schoolsCount: 1, schoolsPct: '100%', studentsTotal: 234, studentsTotalPct: '98%', studentsFemale: 103, studentsFemalePct: '91%', notes: '' },
      { name: 'អប់រំអនាម័យរាងកាយ និងសុខភាព', schoolsCount: 1, schoolsPct: '100%', studentsTotal: 234, studentsTotalPct: '98%', studentsFemale: 103, studentsFemalePct: '91%', notes: '' },
      { name: 'អប់រំការសង្រ្គោះបឋម', schoolsCount: 0, schoolsPct: '0%', studentsTotal: 0, studentsTotalPct: '0%', studentsFemale: 0, studentsFemalePct: '0%', notes: '' },
      { name: 'អប់រំពីកង្វះជាតិអ៊ីយ៉ូត', schoolsCount: 0, schoolsPct: '0%', studentsTotal: 0, studentsTotalPct: '0%', studentsFemale: 0, studentsFemalePct: '0%', notes: '' },
    ],
    activities: 'ណែនាំពីការសម្អាតមាត់ធ្មេញ ការលាងសម្អាតដៃ ការប្រើប្រាស់បង្គន់ និងការសម្អាតខ្លួនប្រាណរៀងរាល់ថ្ងៃ (សម្អាតដៃជើង កាត់ក្រចក កាត់សក់ សម្លៀកបំពាក់ អនាម័យពេលមករដូវ…)',
    challenges: 'សិស្សមួយចំនួនពុំទាន់អនុវត្តបានត្រឹមត្រូវតាមជំហានឬតាមក្បួនខ្នាត និងខ្វះខាតសម្ភារៈ (កន្រ្តៃកាត់ក្រចក កន្រ្តៃកាត់សក់ ច្រាសដុសធ្មេញ ថ្នាំដុសធ្មេញ សាប៊ូលាងដៃ)',
    requests: 'គ្រូបន្ទុកថ្នាក់តាមដានសុខភាព-អនាម័យសិស្សជាប្រចាំ និងបន្ថែមសម្ភារៈអនាម័យឱ្យបានគ្រប់គ្រាន់',
  },
  health: {
    deworming: {
      rounds: [
        { roundName: 'លើកទី១', total: 237, female: 104, totalPct: '99%', femalePct: '98%', other: '0' },
        { roundName: 'លើកទី២', total: 234, female: 102, totalPct: '98%', femalePct: '96%', other: '0' },
        { roundName: 'លើកទី៣', total: 0, female: 0, totalPct: '0%', femalePct: '0%', other: '0' },
        { roundName: 'លើកទី៤', total: 0, female: 0, totalPct: '0%', femalePct: '0%', other: '0' },
      ],
      activities: 'លោកគ្រូអ្នកគ្រូបានទទួលថ្នាំទំលាក់ព្រូនពីប្រធានកម្រង និងបានផ្ដល់ឲ្យសិស្សលេបនៅសាលារៀនជាក់ស្ដែង។',
      challenges: 'សិស្សមួយចំនួនគេចវេស មិនលេបថ្នាំដោយសារខ្លាច ឬមានជំងឺប្រចាំកាយ។',
      requests: 'សូមឲ្យរៀបចំកម្មវិធីពិនិត្យតាមដានសុខភាពសិស្ស ១ខែម្ដង និងផ្តល់វគ្គផ្សព្វផ្សាយដល់មាតាបិតាសិស្ស។',
    },
    sanitation: {
      facilities: [
        { facility: 'បង្គន់អនាម័យ', schoolsCount: 1, totalCount: 2, totalPct: '100%', workingCount: 2, workingPct: '100%', brokenCount: 0, brokenPct: '0%' },
        { facility: 'ស្រះទឹក', schoolsCount: 0, totalCount: 0, totalPct: '0%', workingCount: 0, workingPct: '0%', brokenCount: 0, brokenPct: '0%' },
        { facility: 'អណ្ដូង', schoolsCount: 1, totalCount: 2, totalPct: '100%', workingCount: 1, workingPct: '50%', brokenCount: 1, brokenPct: '50%' },
        { facility: 'ធុងច្រោះទឹកស្អាត', schoolsCount: 1, totalCount: 1, totalPct: '100%', workingCount: 1, workingPct: '100%', brokenCount: 0, brokenPct: '0%' },
      ],
      activities: 'រៀបចំកាលវិភាគសម្អាតបង្គន់ជាប្រចាំសប្តាហ៍ លើកទឹកចិត្តសិស្សឱ្យយកដបទឹកផ្ទាល់ខ្លួនមកទទួលទាន និងបិទស្លាកណែនាំពីការសន្សំសំចៃទឹក។',
      challenges: 'អណ្តូងទឹកចំនួន ១ បានខូចបូមមិនឡើងទឹកនៅរដូវប្រាំង ខ្វះទឹកសម្រាប់ស្រោចសួនបន្លែ និងលាងបង្គន់។',
      requests: 'ស្នើសុំថវិកាជួសជុលអណ្តូងទឹកខូច ១ កន្លែង និងបន្ថែមធុងចម្រោះទឹកស្អាត ១ ទៀត សម្រាប់បន្ទប់បឋម។',
    },
    nutrition: {
      rations: {
        schoolsCount: 0,
        schoolsPct: '0%',
        studentsTotal: 0,
        studentsFemale: 0,
      },
      breakfast: {
        schoolsCount: 0,
        schoolsPct: '0%',
        studentsTotal: 0,
        studentsFemale: 0,
      },
      activities: 'សាលាមិនទាន់ទទួលបានកម្មវិធីផ្ដល់អាហារូបត្ថម្ភពេលព្រឹក និងស្បៀងអាហារពីកម្មវិធីជាតិនៅឡើយទេ។',
      challenges: 'សិស្សក្រីក្រមួយចំនួនមកសាលារៀនទាំងមិនទាន់បានទទួលទានអាហារពេលព្រឹក បណ្តាលឱ្យអស់កម្លាំង និងមិនសូវយកចិត្តទុកដាក់រៀនសូត្រ។',
      requests: 'ស្នើសុំការិយាល័យអប់រំ និងអង្គការដៃគូពិចារណាបញ្ចូលសាលាបឋមសិក្សា រោគ ក្នុងកម្មវិធីផ្តល់អាហារពេលព្រឹក។',
    },
  },
  extracurricular: {
    socialWork: {
      content: 'ដង្ហែសព ចូលរួមបុណ្យកឋិនទាន រើសសំរាមក្នុងសហគមន៍',
      result: 'ចូលរួមដង្ហែសពចំនួន5ដងចម្ងាយ300ម ចូលរួមបុណ្យកឋិនទានចំនួន1ថ្ងៃ និងចូលរួមសម្អាតភូមិចំនួន ៣ពេល',
    },
    agriculture: {
      content: 'ដាំដុះ ដំណាំ …….,,',
      result: '…..,,,,,,',
    },
    studyTour: {
      content: '………..',
      result: '……….',
    },
    sports: {
      competitionsCount: 1,
      schoolLevelClasses: 2,
      clusterTimes: 0,
      districtTimes: 1,
      provinceTimes: 0,
      content: 'បាល់ទាត់ផ្នែកបុរស',
      result: 'ជាប់ចំណាត់ថ្នាក់លេខ២ ពានរង្វាន់រដ្ឋបាលស្រុកភ្នំស្រុក',
    },
    arts: {
      performancesCount: 1,
      schoolLevelClasses: 3,
      clusterTimes: 0,
      districtTimes: 0,
      provinceTimes: 0,
      content: 'របាំជូនពរ និងសម្ដែងរឿងអប់រំខ្លី ក្នុងថ្ងៃទិវាជាតិអំណាន រាំ និងសម្ដែងបានល្អ',
      result: 'ចំនួនសិល្បៈករកើនឡើងបទពិសោធន៍',
    },
  },
  inspection: {
    ministry: { levelName: 'ថ្នាក់ក្រសួងពិនិត្យបាន', schoolsCount: 1, classesCount: 3 },
    province: { levelName: 'ថ្នាក់ខេត្ដចុះពិនិត្យបាន', schoolsCount: 1, classesCount: 6 },
    district: { levelName: 'ថ្នាក់ស្រុកចុះពិនិត្យបាន', schoolsCount: 1, classesCount: 10 },
    cluster: { levelName: 'ថ្នាក់កម្រងចុះពិនិត្យបាន', schoolsCount: 1, classesCount: 10 },
    total: { levelName: 'សរុបថ្នាក់ចុះពិនិត្យបាន', schoolsCount: 1, classesCount: 10 },
    guidanceFeedback: 'ខ្លឹមសារជួយណែនាំ +បទពិសោធន៏ការងារ',
  },
  communityWork: {
    cooperationDetails: 'ទិញសៀវភៅដាក់បណ្ណាល័យ ចំនួន ៨០ក្បាល',
    result: 'សិស្សានុសិស្សទទួលបានសៀវភៅរឿងថ្មីសម្រាប់អានក្នុងបណ្ណាល័យ',
  },
  vacationPrep: {
    tasks: [
      'រៀបចំបញ្ជីឈ្មោះ',
      'ជំរឿន',
      'ចុះឈ្មោះចូលរៀន',
      'រង្វាន់សិស្ស',
      'វេនយាមសាលា',
    ],
    scholarshipListStatus: 'រៀបចំបញ្ជីឈ្មោះសិស្សអាហារូបករណ៍',
  },
  conclusion: {
    generalSummary: 'ក្រោយបញ្ចប់ឆ្នាំសិក្សា សិស្សទទួលបានចំណេះដឹង និងបានឡើងថ្នាក់ សាលាបានបញ្ចប់ផែនការមួយចំនួនធំ និងបន្តអនុវត្តទៅឆ្នាំក្រោយទៀត ។',
    keyAchievements: [
      'ការរៀននិងបង្រៀនកាន់តែល្អប្រសើរសហគមន៍និងដៃគូអភិវឌ្ឍចូលរួមយ៉ាងសកម្មក្នុងការងារអប់រំ',
      'មានការងារគ្រប់គ្រងដឹកនាំគ្រប់កម្រិតថ្នាក់បានពង្រឹងសមត្ថភាពរបស់លោកគ្រូ អ្នកគ្រូ មានការអភិវឌ្ឍជាបណ្តើរៗ ។',
    ],
    challengesToResolve: 'ទន្ទឹមនឹងសម្រេចបាននូវលទ្ធផលដូចរៀបរាប់ខាងលើ សាលាយើងក៏ជួបប្រទះ នឹងបញ្ហាប្រឈមមួយចំនួនដែលត្រូវដោះស្រាយ រួមមាន ម៉ាស៊ីនព្រីន និងប្រភពទឹកប្រើប្រាស់ផ្សេងៗ។',
  },
  aiExecutiveSummary: `របាយការណ៍បូកសរុបលទ្ធផលការងារដំណាច់ឆ្នាំ ផ្នែកបឋមសិក្សា ឆ្នាំសិក្សា ២០២៥-២០២៦ របស់សាលាបឋមសិក្សា រោគ បង្ហាញពីវឌ្ឍនភាពគួរឱ្យកត់សម្គាល់៖
១. អត្រាជាប់ចុងឆ្នាំសរុបសម្រេចបាន ៩៨.៤% ដោយសិស្សជាប់ចុងឆ្នាំសរុប ២៤២ នាក់ (ស្រី ១១៣ នាក់) លើសិស្សដំណាច់ឆ្នាំ ២៤៦ នាក់។
២. អត្រាសិស្សបោះបង់ការសិក្សាស្ថិតក្នុងកម្រិតទាប ១.៦% (៤ នាក់ នៅថ្នាក់ទី៤ និងទី៦ ដោយសារការចំណាកស្រុក)។
៣. ការអនុវត្តកម្មវិធីសិក្សាសម្រេចបានខ្ពស់លើមុខវិជ្ជាភាសាខ្មែរ (៩១%) គណិតវិទ្យា (៩០%) ខណៈភាសាអង់គ្លេសនៅកម្រិត ៧៧%។
៤. ការងារសុខភាពសិក្សា និងអនាម័យសម្រេចបានល្អប្រសើរ ជាមួយនឹងការទម្លាក់ព្រូនបាន ៩៨-៩៩% និងអប់រំអនាម័យមាត់ធ្មេញបានទូទាំងសាលា។
បញ្ហាប្រឈមចម្បងរួមមាន អណ្តូងទឹកខូចចំនួន ១ បង្កការលំបាកក្នុងការប្រើប្រាស់ទឹកនៅរដូវប្រាំង និងតម្រូវការកម្មវិធីអាហារពេលព្រឹកសម្រាប់សិស្សខ្វះខាត។`,
  aiRecommendations: [
    'ស្នើសុំការិយាល័យអប់រំស្រុក និងអាជ្ញាធរឃុំ ជួយជួសជុលអណ្តូងទឹកដែលខូច ១ កន្លែងឱ្យបានទាន់ពេលវេលាមុនរដូវប្រាំងចូលមកដល់។',
    'ពង្រឹងការបង្រៀនភាសាអង់គ្លេសនៅកម្រិតថ្នាក់ទី៤ ដល់ទី៦ និងបំប៉នវិធីសាស្ត្របង្រៀនដល់លោកគ្រូ-អ្នកគ្រូ។',
    'ចុះសួរសុខទុក្ខ និងអន្តរាគមន៍ជាមួយគ្រួសារសិស្សប្រឈមមុខនឹងការបោះបង់ការសិក្សា ដោយសារការចំណាកស្រុករបស់មាតាបិតា។',
    'កៀរគរការគាំទ្រពីអង្គការទស្សនៈពិភពលោក (WVSI) និងអង្គការសាលាបៃតង ដើម្បីផ្តល់សម្ភារៈអនាម័យ និងបន្តកម្មវិធីកែលម្អបរិស្ថានសាលា។',
  ],
  lastUpdated: '2026-09-13',
};
